



 
 
 



 
 
 



 
 
 



 
 
 



 
 
 



 
 
 



 



 
 
 
 


 CREATE TABLE QUALITY_RESULTS_DBOUTPUT 
(
      PLAN_NAME VARCHAR ,
      DESCRIPTION VARCHAR ,
      QUANTITY NUMERIC ,
      ITEM_NUMBER VARCHAR ,
      LOT_NUMBER VARCHAR ,
      SUPPLIER VARCHAR ,
      PO_NUMBER VARCHAR ,
      SO_NUMBER VARCHAR ,
      CUST_ACCOUNT_NUMBER VARCHAR ,
      CHARACTER1 VARCHAR ,
      CHARACTER2 VARCHAR ,
      CHARACTER3 VARCHAR ,
      CHARACTER4 VARCHAR ,
      CHARACTER5 VARCHAR ,
      CHARACTER6 VARCHAR ,
      CHARACTER7 VARCHAR ,
      CHARACTER8 VARCHAR ,
      CHARACTER9 VARCHAR ,
      CHARACTER10 VARCHAR ,
      COLLECTION_ID NUMERIC ,
      OCCURRENCE NUMERIC  NOT NULL,
      LAST_UPDATE_DATE VARCHAR ,
      QA_LAST_UPDATE_DATE VARCHAR ,
      TXN_HEADER_ID NUMERIC ,
      ORGANIZATION_ID NUMERIC ,
      PLAN_ID NUMERIC ,
      SPEC_ID NUMERIC ,
      ITEM_ID NUMERIC ,
      QA_LAST_UPDATED_BY_NAME VARCHAR ,
      QA_CREATED_BY_NAME VARCHAR ,
      QA_CREATION_DATE VARCHAR ,
      PROMPT1 VARCHAR ,
      PROMPT2 VARCHAR ,
      PROMPT3 VARCHAR ,
      PROMPT4 VARCHAR ,
      PROMPT5 VARCHAR ,
      PROMPT6 VARCHAR ,
      PROMPT7 VARCHAR ,
      PROMPT8 VARCHAR ,
      PROMPT9 VARCHAR ,
      PROMPT10 VARCHAR ,
      MF1PROMPT VARCHAR ,
      MF2PROMPT VARCHAR ,
      MF3PROMPT VARCHAR ,
      MF4PROMPT VARCHAR ,
      MF1VALUE VARCHAR ,
      MF2VALUE VARCHAR ,
      MF3VALUE VARCHAR ,
      MF4VALUE VARCHAR ,
      PROMPT11 VARCHAR ,
      PROMPT12 VARCHAR ,
      PROMPT13 VARCHAR ,
      PROMPT14 VARCHAR ,
      PROMPT15 VARCHAR ,
      PROMPT16 VARCHAR ,
      PROMPT17 VARCHAR ,
      PROMPT18 VARCHAR ,
      PROMPT19 VARCHAR ,
      PROMPT20 VARCHAR ,
      PROMPT21 VARCHAR ,
      PROMPT22 VARCHAR ,
      PROMPT23 VARCHAR ,
      PROMPT24 VARCHAR ,
      PROMPT25 VARCHAR ,
      PROMPT26 VARCHAR ,
      PROMPT27 VARCHAR ,
      PROMPT28 VARCHAR ,
      PROMPT29 VARCHAR ,
      PROMPT30 VARCHAR ,
      CHARACTER11 VARCHAR ,
      CHARACTER12 VARCHAR ,
      CHARACTER13 VARCHAR ,
      CHARACTER14 VARCHAR ,
      CHARACTER15 VARCHAR ,
      CHARACTER16 VARCHAR ,
      CHARACTER17 VARCHAR ,
      CHARACTER18 VARCHAR ,
      CHARACTER19 VARCHAR ,
      CHARACTER20 VARCHAR ,
      CHARACTER21 VARCHAR ,
      CHARACTER22 VARCHAR ,
      CHARACTER23 VARCHAR ,
      CHARACTER24 VARCHAR ,
      CHARACTER25 VARCHAR ,
      CHARACTER26 VARCHAR ,
      CHARACTER27 VARCHAR ,
      CHARACTER28 VARCHAR ,
      CHARACTER29 VARCHAR ,
      CHARACTER30 VARCHAR ,
    CONSTRAINT QUALITY_RESULTS_DBOUTPUT_PK PRIMARY KEY(OCCURRENCE)
);
  CREATE TABLE QUALITY_PLANDETAILS_OUTPUT 
(
      PLAN_NAME VARCHAR ,
      PLAN_ID NUMERIC  NOT NULL,
    CONSTRAINT QUALITY_PLANDETAILS_OUTPUT_PK PRIMARY KEY(PLAN_ID)
);
  CREATE TABLE INVENTORY_DETAIL_BSOUTPUT 
(
      ORGANIZATION_ID NUMERIC  NOT NULL,
      ORGANIZATION_CODE VARCHAR ,
    CONSTRAINT INVENTORY_DETAIL_BSOUTPUT_PK PRIMARY KEY(ORGANIZATION_ID)
);
  CREATE TABLE PLAN_ELEMENT_DB_ADAPTER_OUTPUT 
(
      NAME VARCHAR  NOT NULL,
      ORGANIZATION_ID NUMERIC ,
      ITEM_NUMBER_PROMPT VARCHAR ,
      TRX_NUMBER_PROMPT VARCHAR ,
      TXN_HEADER_IDPROMPT VARCHAR ,
      ORGANIZATION_IDPROMPT VARCHAR ,
      SPEC_IDPROMPT VARCHAR ,
      TRANSACTION_IDPROMPT VARCHAR ,
      DEPARTMENT_IDPROMPT VARCHAR ,
      TO_DEPARTMENT_IDPROMPT VARCHAR ,
      RESOURCE_IDPROMPT VARCHAR ,
      QUANTITY_PROMPT VARCHAR ,
      UOM_PROMPT VARCHAR ,
      REVISION_PROMPT VARCHAR ,
      SUBINVENTORY_PROMPT VARCHAR ,
      LOCATORID_PROMPT VARCHAR ,
      LOT_NUMBER_PROMPT VARCHAR ,
      SERIAL_NUMBER_PROMPT VARCHAR ,
      COMP_ITEM_ID_PROMPT VARCHAR ,
      COMP_UOMPROMPT VARCHAR ,
      COMP_REVISION_PROMPT VARCHAR ,
      COMP_SUBINVENTORY_PROMPT VARCHAR ,
      COMP_LOCATOR_ID_PROMPT VARCHAR ,
      COMP_LOT_NUMBER_PROMPT VARCHAR ,
      COMP_SERIAL_NUMBER_PROMPT VARCHAR ,
      WIP_ENTITY_ID_PROMPT VARCHAR ,
      LINE_ID_PROMPT VARCHAR ,
      FROM_OP_SEQ_NUM_PROMPT VARCHAR ,
      TO_OP_SEQ_NUM_PROMPT VARCHAR ,
      VENDOR_IDPROMPT VARCHAR ,
      RECEIPT_NUM_PROMPT VARCHAR ,
      PO_NUMBER_PROMPT VARCHAR ,
      PO_LINE_NUMBER_PROMPT VARCHAR ,
      PO_RELEASE_IDPROMPT VARCHAR ,
      PO_SHIPMENT_NUM_PROMPT VARCHAR ,
      CUSTOMER_IDPROMPT VARCHAR ,
      SO_HEADER_IDPROMPT VARCHAR ,
      RMA_HEADER_IDPROMPT VARCHAR ,
      TRANSACTION_DATE_PROMPT VARCHAR ,
      STATUS_PROMPT VARCHAR ,
      PROJECT_IDPROMPT VARCHAR ,
      TASK_IDPROMPT VARCHAR ,
      XFR_LPN_IDPROMPT VARCHAR ,
      CONTRACT_IDPROMPT VARCHAR ,
      CONTRACT_LINE_IDPROMPT VARCHAR ,
      DELIVERABLE_IDPROMPT VARCHAR ,
      ASSET_GROUP_IDPROMPT VARCHAR ,
      ASSET_NUMBER_PROMPT VARCHAR ,
      ASSET_ACTIVITY_IDPROMPT VARCHAR ,
      FOLLOWUP_ACTIVITY_IDPROMPT VARCHAR ,
      WORK_ORDER_IDPROMPT VARCHAR ,
      CHARACTER1PROMPT VARCHAR ,
      CHARACTER2PROMPT VARCHAR ,
      CHARACTER3PROMPT VARCHAR ,
      CHARACTER4PROMPT VARCHAR ,
      CHARACTER5PROMPT VARCHAR ,
      CHARACTER6PROMPT VARCHAR ,
      CHARACTER7PROMPT VARCHAR ,
      CHARACTER8PROMPT VARCHAR ,
      CHARACTER9PROMPT VARCHAR ,
      CHARACTER10PROMPT VARCHAR ,
      CHARACTER11PROMPT VARCHAR ,
      CHARACTER12PROMPT VARCHAR ,
      CHARACTER13PROMPT VARCHAR ,
      CHARACTER14PROMPT VARCHAR ,
      CHARACTER15PROMPT VARCHAR ,
      CHARACTER16PROMPT VARCHAR ,
      CHARACTER17PROMPT VARCHAR ,
      CHARACTER18PROMPT VARCHAR ,
      CHARACTER19PROMPT VARCHAR ,
      CHARACTER20PROMPT VARCHAR ,
      CHARACTER21PROMPT VARCHAR ,
      CHARACTER22PROMPT VARCHAR ,
      CHARACTER23PROMPT VARCHAR ,
      CHARACTER24PROMPT VARCHAR ,
      CHARACTER25PROMPT VARCHAR ,
      CHARACTER26PROMPT VARCHAR ,
      CHARACTER27PROMPT VARCHAR ,
      CHARACTER28PROMPT VARCHAR ,
      CHARACTER29PROMPT VARCHAR ,
      CHARACTER30PROMPT VARCHAR ,
      ITEM_NUMBER_MF_FLAG VARCHAR ,
      TRX_NUMBER_MF_FLAG VARCHAR ,
      TXN_HEADER_IDMF_FLAG VARCHAR ,
      ORGANIZATION_IDMF_FLAG VARCHAR ,
      SPEC_IDMF_FLAG VARCHAR ,
      TRANSACTION_IDMF_FLAG VARCHAR ,
      DEPARTMENT_IDMF_FLAG VARCHAR ,
      TO_DEPARTMENT_IDMF_FLAG VARCHAR ,
      RESOURCE_IDMF_FLAG VARCHAR ,
      QUANTITY_MF_FLAG VARCHAR ,
      UOM_MF_FLAG VARCHAR ,
      REVISION_MF_FLAG VARCHAR ,
      SUBINVENTORY_MF_FLAG VARCHAR ,
      LOCATORID_MF_FLAG VARCHAR ,
      LOT_NUMBER_MF_FLAG VARCHAR ,
      SERIAL_NUMBER_MF_FLAG VARCHAR ,
      COMP_ITEM_ID_MF_FLAG VARCHAR ,
      COMP_UOMMF_FLAG VARCHAR ,
      COMP_REVISION_MF_FLAG VARCHAR ,
      COMP_SUBINVENTORY_MF_FLAG VARCHAR ,
      COMP_LOCATOR_ID_MF_FLAG VARCHAR ,
      COMP_LOT_NUMBER_MF_FLAG VARCHAR ,
      COMP_SERIAL_NUMBER_MF_FLAG VARCHAR ,
      WIP_ENTITY_ID_MF_FLAG VARCHAR ,
      LINE_ID_MF_FLAG VARCHAR ,
      FROM_OP_SEQ_NUM_MF_FLAG VARCHAR ,
      TO_OP_SEQ_NUM_MF_FLAG VARCHAR ,
      VENDOR_IDMF_FLAG VARCHAR ,
      RECEIPT_NUM_MF_FLAG VARCHAR ,
      PO_NUMBER_MF_FLAG VARCHAR ,
      PO_LINE_NUMBER_MF_FLAG VARCHAR ,
      PO_RELEASE_IDMF_FLAG VARCHAR ,
      PO_SHIPMENT_NUM_MF_FLAG VARCHAR ,
      CUSTOMER_IDMF_FLAG VARCHAR ,
      SO_HEADER_IDMF_FLAG VARCHAR ,
      RMA_HEADER_IDMF_FLAG VARCHAR ,
      TRANSACTION_DATE_MF_FLAG VARCHAR ,
      STATUS_MF_FLAG VARCHAR ,
      PROJECT_IDMF_FLAG VARCHAR ,
      TASK_IDMF_FLAG VARCHAR ,
      XFR_LPN_IDMF_FLAG VARCHAR ,
      CONTRACT_IDMF_FLAG VARCHAR ,
      CONTRACT_LINE_IDMF_FLAG VARCHAR ,
      DELIVERABLE_IDMF_FLAG VARCHAR ,
      ASSET_GROUP_IDMF_FLAG VARCHAR ,
      ASSET_NUMBER_MF_FLAG VARCHAR ,
      ASSET_ACTIVITY_IDMF_FLAG VARCHAR ,
      FOLLOWUP_ACTIVITY_IDMF_FLAG VARCHAR ,
      WORK_ORDER_IDMF_FLAG VARCHAR ,
      CHARACTER1MF_FLAG VARCHAR ,
      CHARACTER2MF_FLAG VARCHAR ,
      CHARACTER3MF_FLAG VARCHAR ,
      CHARACTER4MF_FLAG VARCHAR ,
      CHARACTER5MF_FLAG VARCHAR ,
      CHARACTER6MF_FLAG VARCHAR ,
      CHARACTER7MF_FLAG VARCHAR ,
      CHARACTER8MF_FLAG VARCHAR ,
      CHARACTER9MF_FLAG VARCHAR ,
      CHARACTER10MF_FLAG VARCHAR ,
      CHARACTER11MF_FLAG VARCHAR ,
      CHARACTER12MF_FLAG VARCHAR ,
      CHARACTER13MF_FLAG VARCHAR ,
      CHARACTER14MF_FLAG VARCHAR ,
      CHARACTER15MF_FLAG VARCHAR ,
      CHARACTER16MF_FLAG VARCHAR ,
      CHARACTER17MF_FLAG VARCHAR ,
      CHARACTER18MF_FLAG VARCHAR ,
      CHARACTER19MF_FLAG VARCHAR ,
      CHARACTER20MF_FLAG VARCHAR ,
      CHARACTER21MF_FLAG VARCHAR ,
      CHARACTER22MF_FLAG VARCHAR ,
      CHARACTER23MF_FLAG VARCHAR ,
      CHARACTER24MF_FLAG VARCHAR ,
      CHARACTER25MF_FLAG VARCHAR ,
      CHARACTER26MF_FLAG VARCHAR ,
      CHARACTER27MF_FLAG VARCHAR ,
      CHARACTER28MF_FLAG VARCHAR ,
      CHARACTER29MF_FLAG VARCHAR ,
      CHARACTER30MF_FLAG VARCHAR ,
    CONSTRAINT PLAN_ELEMENT_DB_ADAPTER_OUTPUT_PK PRIMARY KEY(NAME)
);
 

CREATE TABLE DATA_SYNCH_ACTIONS 
(
      ID NUMERIC NOT NULL,
      SERVICE_CLASS_NAME VARCHAR NOT NULL,
      ENTITY_CLASS_NAME VARCHAR NOT NULL,
      JSON_PAYLOAD VARCHAR ,
      ACTION VARCHAR NOT NULL,
      DATE_CREATED DATE NOT NULL,
      DATE_LAST_SYNCH DATE NOT NULL,
      LAST_SYNCH_ERROR VARCHAR,
      CUSTOM_METHOD_NAME VARCHAR,
    CONSTRAINT DSA_PK PRIMARY KEY(SERVICE_CLASS_NAME ,ID)
);

CREATE TABLE WEB_SERVICE_CALL 
(
      ID NUMERIC  NOT NULL,
      CONNECTION VARCHAR ,
      REQUEST VARCHAR ,
      METHOD VARCHAR ,
      REQUEST_HEADERS VARCHAR ,
      DURATION NUMERIC ,
      REQUEST_PAYLOAD VARCHAR ,
      RESPONSE_PAYLOAD VARCHAR ,
      ERROR_MESSAGE VARCHAR ,
      TIMESTAMP DATE ,
    CONSTRAINT WEB_SERVICE_CALL_PK PRIMARY KEY(ID)
);
